apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello
  labels:
    app: spring-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
      - name: spring-hello
        image: spring-hello-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080