name: CI for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Hoặc 'zulu', 'corretto'
          java-version: '17'
          cache: maven  # Cache dependencies

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test
