name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Lấy toàn bộ lịch sử

      - name: Debug Git Commit
        run: git rev-parse HEAD  # Kiểm tra commit hợp lệ

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Docker-main  # Thư mục chứa Dockerfile
          file: ./Docker-main/Dockerfile  # Chỉ định tệp Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-image:latest
            ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}

      - name: Image digest
        run: echo "Docker image digest is ${{ steps.docker_build.outputs.digest }}"
