name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Docker-main  # ⚠ Đường dẫn này phải trỏ đến thư mục chứa Dockerfile
          file: ./Docker-main/Dockerfile  # ⚠ Cập nhật đường dẫn chính xác của Dockerfile
          push: true
          tags: your-dockerhub-username/your-image-name:latest
